### ISSUE TITLE
UI for default configuration of animation

### ISSUE THREAD

**Issue by martin5040** [itemir/signalk-saillogger#11]
The default map view for animation seems to have recently changed from OpenStreetMaps to Satellite. I’m quite enjoying the change, but guess others won’t! I see from the FAQ screen that you can enter a custom URL to control the view, but that’s a bit cumbersome to do on a regular basis to get a particular view, especially as you’d have to do it afresh for each passage.

Could you add configuration options for the default time-lapse view to the user’s preferences page?

**Comment by itemir** [comment]
This is now available under[https://saillogger.com/timelapse/customize/]( https://saillogger.com/timelapse/customize/)
