### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by billknny** [itemir/signalk-saillogger#23]
I am running into an issue when trying to install onto a Cerbo GX running Venus 3.01 Large.  The Signal K server reports that  saillogger Failed to start.  Obviously I am missing something on my system that it expects to be there.

Here is the applicable pieces from the Server Log on restart:
![Screenshot 2023-09-04 at 14 12 43](https://github.com/itemir/signalk-saillogger/assets/144057959/8f10fcc0-5f33-461b-8dc2-1fcc13e84eb1)

Here are the currently installed SignalK apps:
![Screenshot 2023-09-04 at 14 12 09](https://github.com/itemir/signalk-saillogger/assets/144057959/d03b84e4-85be-40cf-90b0-430c461df492)

Any guidance would be greatly appreciated!

**Comment by itemir** [comment]
Looks like the installation failed. Sqlite is compiled from the source during installation and can take a really long time on the Cerbo. It may have been interrupted. Can you remove Saillogger, restart Signal K and reinstall it and then restart it when it finishes? Be patient during the install though, can take a long time. Don’t restart until installation completes.

**Comment by billknny** [comment]
Thanks for a quick response.  I really appreciate your efforts on this.  I have a pretty good idea of what’s involved.

It seems that there is something wrong with my SignalK server itself.  The Sailogger does not show up as “Available” and every time I restart, it shows the same error message, even if I did not re-install it.  As an additional test I tred to delete another application, and that also failed.  It reported that it was deleted, but it remained in place.  I am thinking that a full clean install of the server is needed…  as soon as I figure out how to do that without a compete factory reset of the Cerbo...

Bill

**Comment by mpvader** [comment]
Hi, right now the only way to do that is login on ssh, and delete /data/conf/signalk.

We are working on an easier way to reset signalk without resetting the rest. But that might take a few weeks:

https://github.com/victronenergy/venus/issues/1139

**Comment by billknny** [comment]
Thank you for that!  While it is not exactly the answer I had hoped for, it does give me a path forward I can try.  

As always, Victron support is the best.

**Comment by billknny** [comment]
Just to close this out… 

I did as suggested, and manually deleted /data/conf/signalk  from the Cerbo. Restarted from scratch, and everything installed fine.

Thanks again for the help.

**Comment by mpvader** [comment]
Good to hear! Always nice to hear if something ends out well.

Often the only response is when there are further issues ;o)

**Comment by itemir** [comment]
Indeed! And that is a particular reason why Saillogger is awesome on a Victron!
