### ISSUE TITLE
Public profile not working

### ISSUE THREAD

**Issue by cherrymcgerry** [itemir/signalk-saillogger#25]
Navigating to a page enabled as public always results in a request to login.

This has only been happening for a few days, before it was working without a problem.
I'm unable to verify if this is also the case for other users.

For example, timelapse is enabled under public profile yet it always redirects to the authentication page.
https://saillogger.com/timelapse/487/
This is the case for all pages regardless if they are enabled or disabled.

One thing worth mentioning but I don't see how it would have any effect on this.
I had changed the sendMonitoringData function to just get the position data instead of checking for the most recent in the timestamp as I have an old gps that has an incorrect date and time due to date rollover.

I'm unsure what I can do to troubleshoot this.

**Comment by itemir** [comment]
This was a regression, it is fixed. Please try again.

**Comment by cherrymcgerry** [comment]
Indeed, thank you for the quick response and resolving!
