### ISSUE TITLE
Feature request: public profile address

### ISSUE THREAD

**Issue by bhavers** [itemir/signalk-saillogger#3]
I see that i can set my profile to public in preferences.
I guess this means that single trips can be viewed by others when vistors have the link to a trip.
I would like to give some people one link to all my trips.
Would it be possible to have an address with the boat name that leads not logged in visitors to the log overview page?
Something link saillogger.com/public/boatname

**Comment by itemir** [comment]
This makes sense. I will add this to the list of enhancements I am planning.

**Comment by bhavers** [comment]
Great!

**Comment by itemir** [comment]
This is there now. If you check your preferences, you will see a new option to make your logs list public. Check it on and go to your logs list view page, it should be viewable by others as well on the same URL. You can test in an incognito window.

**Comment by bhavers** [comment]
👍 that works well.
Maybe add, for new users, a short description that their loga url would be the link to share.

thanks!
