### ISSUE TITLE
Annotate Tracks

### ISSUE THREAD

**Issue by martin5040** [itemir/signalk-saillogger#9]
We already have the functionality to click on a point on a track, and see speed or optionally delete the point. How about adding the ability to enter a short comment about that point? For example, to say “turning round wind farm” or “here I came head to wind to reef”, etc. Such comments could then appear during the time-lapse display, giving a richer view of what was going on.

**Comment by itemir** [comment]
It is now possible to add notes to tracepoints. Open a log, click on a tracepoint on the map and add a note. Those notes are also included in Timelapse animations so you can create memories of your sails and view them Timelapse.
